GO_GOLANGCI_LINT_ARGUMENTS: --timeout 10m
GO_REVIVE_ARGUMENTS: -formatter friendly -config .revive.toml
REPOSITORY_KICS_ARGUMENTS: --exclude-paths dev --fail-on high
REPOSITORY_TRIVY_ARGUMENTS: --severity HIGH,CRITICAL
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
