app:
  log-level: info
  concurrency: 5

gpas:
  domains:
    - patient: PATIENT
    - encounter: ENC
  url: http://localhost:18080/gpas/DomainService?wsdl
  auth:
    basic:
      username:
      password:

fhir:
  provider:
    mongodb:
      connection: mongodb://localhost
      batch-size: 5000
  pseudonymizer:
    url: http://localhost:5000/fhir
    auth:
      basic:
        username:
        password:
    retry:
      count: 10
      timeout: 10
      wait: 5
      max-wait: 20
