app:
  log-level: info
  concurrency: 5

gpas:
  url:

fhir:
  provider:
    mongodb:
      connection: mongodb://localhost
      batch-size: 5000
  pseudonymizer:
    url: http://localhost:5000/fhir
    retry:
      count: 10
      timeout: 10
      wait: 5
      max-wait: 20
