services:

  mongo:
    image: mongo:7.0.5
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

  gpas:
    image: harbor.miracum.org/gpas/gpas:1.13.1-20230127
    ports:
      - "18080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - ./sqls/:/docker-entrypoint-initdb.d/
    command: --max_allowed_packet=20M --default-time-zone=Europe/Berlin

  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.21.9
    environment:
      UseSystemTextJsonFhirSerializer: true
      GPAS__URL: "http://gpas:8080/ttp-fhir/fhir/gpas/"
      gPAS__Version: 1.13.1
      Features__ConditionalReferencePseudonymization: true
    volumes:
      - ./anonymization.yaml:/etc/anonymization.yaml:ro
    ports:
      - "5000:8080"
    depends_on:
      - gpas
